version: "3.9"

services:
  mysql:
#    container_name: mysql
    image: mysql:8.4
    hostname: ${MYSQL_HOST}
    environment:
#      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    command: [ "--max_connections=500" ]
    volumes:
      - ./docker/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql
      - mysql:/var/lib/mysql
    networks:
      - auction-network

volumes:
  mysql:

networks:
  auction-network:
    driver: bridge
    name: auction-network